[build]
  publish = "public"
  command = "npm run build"
  GATSBY_PAYPAL_KEY = 'sexret'
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  ACCESS_TOKEN = "super secret4"

[context.production]
  publish = "project/output/"
  command = "make publish"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "8.0.1" }

# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview]
  ACCESS_TOKEN = "not so secret 3"

# Here is another way to define context specific environment variables.
[context.deploy-preview.environment]
  ACCESS_TOKEN = "not so secret"

# Branch Deploy context: all deploys that are not from a pull/merge request or
# from the Production branch will inherit these settings.
[context.branch-deploy]
  command = "echo branch"
[context.branch-deploy.environment]
  ACCESS_TOKEN = "not so secret 2"
  NODE_ENV = "development"
